### ISSUE TITLE
file name rests in ext2, ext4, ntfs

### ISSUE THREAD

**Issue by UlrichBerntien** [ivoprogram/overwrite-testing#10]
In a test directory 140 files were created. All file names are 10 character long.
From the 140 files 8 files are deleted.
Then overwrite version 1.5.2 was called to overwrite the metadata of the 8 deleted files.

The result depends on the used file system:
- FAT, exFAT, vFAT: all file names removed.
- ext2, ext4 without journal: 4 of the 8 file names are partial readable. The first 2 characters are overwritten the next 8 characters are readable.
- ntfs: 2 of the 8 file names are readable.

See  [05_random_names.log](https://github.com/ivoprogram/overwrite-testing/blob/master/UlrichBerntien/05_random_names.log) and [05_random_names.sh](https://github.com/ivoprogram/overwrite-testing/blob/master/UlrichBerntien/05_random_names.sh)

Cause is not yet analysed. Bug in test script or in overwrite program is possible.

**Comment by ivoprogram** [comment]
Thank you @UlrichBerntien for your valuable contribution, I have mention your contribution in readme file in this project.

**Comment by ivoprogram** [comment]
I will see this issues when I have time, I think I know the cause and solution.

**Comment by ivoprogram** [comment]
After testing of this version if there are no other suggestions and solutions I will create release and leave this project in pause for a while.

I thing very good project was created, a solution for many cases, it is fine like this.

**Comment by ivoprogram** [comment]
Thank you for the contribution.

The development phase of this project has been finished, the objectives has been achived.
The project is not in development any more.
