### ISSUE TITLE
-dirs:number

### ISSUE THREAD

**Issue by UlrichBerntien** [ivoprogram/overwrite-testing#3]
The parameter -dirs:5 is not enough to overwrite 10 directory entries with long (enough) names in the ext4 file system (and in the FAT file system).
The current documentation contains this behavior for FAT only.

**Comment by ivoprogram** [comment]
You mean -dirs:10 for 5 metadata entries.
Yes I will fix this, I should say more precisely depending on file name length or something, not 2 on 1, and also to write for Ext4.
Thank you

**Comment by ivoprogram** [comment]
Fixed this issue, I have added in program page section Limitations and explained this issues.
https://ivoprogram.github.io/?content=overwrite.html

**Comment by UlrichBerntien** [comment]
Now for me this behaviour is well documented.
